Update CHANGELOG.md
llpereiras/activeadmin pull request #1
Opened 2023-05-08 19:04 UTC by llpereiras

2023-05-08 19:07 UTC, llpereiras commented on CHANGELOG.md
> -
avvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

2023-05-08 20:15 UTC, llpereiras commented
general comment

2023-05-08 20:15 UTC, w-osilva commented
Mensagem na home do PR

2023-05-08 20:17 UTC, w-osilva requested changes
Comentário na aprovação/solicitação de mudança do PR

2023-05-08 20:29 UTC, w-osilva commented on CHANGELOG.md
Comentário na linha do arquivo

2023-05-16 14:40 UTC, w-osilva commented on CHANGELOG.md
> -
Comentando na Thread

2023-05-16 17:31 UTC, w-osilva commented
> Mensagem na home do PR

Replica em um comentario do PR

2023-05-16 17:31 UTC, w-osilva commented
> > Mensagem na home do PR
> 
> Replica em um comentario do PR

Replica da réplica

2023-05-16 17:32 UTC, w-osilva commented on CHANGELOG.md
Replica em comentário de review

2023-05-16 17:33 UTC, w-osilva approved these changes
Comentário de aprovação

2023-10-10 21:25 UTC, closed without merging